# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8790625b9f7d16a4d855db5db5e3eca40ddbabc915b60dc4aa8054bbd5dffdd42b72cb9a8f27e82f05604fc6e03a4f4b1a2f3da131add6d00eb60245e63c3456

test:
  secret_key_base: 4e5a7ea3ff4e1719b4781c281591270ef5f2d473a524975cc68a89c158e58d4430d71621a2d32cf4a40a1f8c29d7872ad9dac5ed9c89a8358bcb928ac75ee7f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
