development:
  adapter: postgresql
  host: localhost
  database: howtoedibles
  username: renato
  password:
  port: 5432

test:
  adapter: postgresql
  host: localhost
  database: howtoedibles-test
  username: renato
  password:
  port: 5432
# development:
#   adapter: postgresql
#   host: ec2-107-21-255-2.compute-1.amazonaws.com
#   database: d40m8atcdop9bc
#   username: epupzauexpqvkn
#   password: ed37bddca20f20ccb1bb31988a15fc45c2f61e512fae0005d6409c4ef79d8d44
#   port: 5432

# AWS
production:
  adapter: postgresql
  host: howtoedibles.c3yz5xc5lumn.us-east-1.rds.amazonaws.com
  database: howtoedibles-production
  username: stoneroot
  password: "L0nd0n&weed420"
  port: 5432

# production:
#   encoding: utf8
#   pool: 15

laricando:
  adapter: postgresql
  host: howtoedibles.c3yz5xc5lumn.us-east-1.rds.amazonaws.com
  database: laricando-production
  username: stoneroot
  password: "L0nd0n&weed420"
  port: 5432
