development:
  adapter: postgresql
  host: localhost
  username: postgres
  database: howtoedibles-development

test:
  adapter: postgresql
  host: localhost
  username: postgres
  database: howtoedibles-test

production:
  adapter: postgresql
  host: localhost
  username: postgres
  database: howtoedibles-production