test:
  features:
    ads_puffnetwork: false
    ads_adsense: true
production:
  features:
    ads_puffnetwork: false
    ads_adsense: true
development:
  features:
    ads_puffnetwork: false
    ads_adsense: true