octopus:
  environments:
    - production
    - development
  development:
    howtoedibles:
      host: howtoedibles.c3yz5xc5lumn.us-east-1.rds.amazonaws.com
      adapter: postgresql
      database: howtoedibles-production
      username: stoneroot
      password: "L0nd0n&weed420"
    laricando:
      host: howtoedibles.c3yz5xc5lumn.us-east-1.rds.amazonaws.com
      adapter: postgresql
      database: laricando-production
      username: stoneroot
      password: "L0nd0n&weed420"
  production:
    laricando:
      host: howtoedibles.c3yz5xc5lumn.us-east-1.rds.amazonaws.com
      adapter: postgresql
      database: howtoedibles-production
      username: stoneroot
      password: "L0nd0n&weed420"
    howtoedibles:
      host: howtoedibles.c3yz5xc5lumn.us-east-1.rds.amazonaws.com
      adapter: postgresql
      database: laricando-production
      username: stoneroot
      password: "L0nd0n&weed420"

