#!/usr/bin/env ruby
# scripts/translate_recipes.rb
# Translates recipe ingredients and instructions using term mapping.
# Run: ruby scripts/translate_recipes.rb

require "json"

ROOT_DIR = File.expand_path("..", __dir__)
TEXT_FILE = File.join(ROOT_DIR, "data", "recipes_text.json")
I18N_DIR = File.join(ROOT_DIR, "i18n")

recipes = JSON.parse(File.read(TEXT_FILE))

# ─────────────────────────────────────────────────────
# Translation dictionaries — cooking terms
# ─────────────────────────────────────────────────────

PT = {
  # Measurements
  "cup" => "xícara", "cups" => "xícaras",
  "tablespoon" => "colher de sopa", "tablespoons" => "colheres de sopa",
  "tbsp" => "colher de sopa",
  "teaspoon" => "colher de chá", "teaspoons" => "colheres de chá",
  "tsp" => "colher de chá",
  "ounce" => "onça", "ounces" => "onças", "oz" => "oz",
  "pound" => "libra", "pounds" => "libras", "lb" => "lb",
  "pinch" => "pitada",
  "handful" => "punhado",
  "slice" => "fatia", "slices" => "fatias",
  "piece" => "pedaço", "pieces" => "pedaços",
  "clove" => "dente", "cloves" => "dentes",
  "bunch" => "maço",
  "can" => "lata",
  "jar" => "pote",
  "package" => "pacote",
  "stick" => "tablete", "sticks" => "tabletes",
  "dash" => "pitada",
  "to taste" => "a gosto",
  "as needed" => "conforme necessário",

  # Common ingredients
  "ground weed" => "erva moída",
  "ground cannabis" => "cannabis moída",
  "cannabutter" => "manteiga de cannabis",
  "cannabis butter" => "manteiga de cannabis",
  "infused coconut oil" => "óleo de coco infusionado",
  "infused olive oil" => "azeite infusionado",
  "infused butter" => "manteiga infusionada",
  "infused honey" => "mel infusionado",
  "infused milk" => "leite infusionado",
  "infused ghee" => "ghee infusionado",
  "infused condensed milk" => "leite condensado infusionado",
  "coconut oil" => "óleo de coco",
  "olive oil" => "azeite de oliva",
  "unsalted butter" => "manteiga sem sal",
  "butter" => "manteiga",
  "sugar" => "açúcar",
  "brown sugar" => "açúcar mascavo",
  "powdered sugar" => "açúcar de confeiteiro",
  "flour" => "farinha",
  "all-purpose flour" => "farinha de trigo",
  "almond flour" => "farinha de amêndoa",
  "baking soda" => "bicarbonato de sódio",
  "baking powder" => "fermento em pó",
  "vanilla extract" => "extrato de baunilha",
  "vanilla" => "baunilha",
  "salt" => "sal",
  "pepper" => "pimenta",
  "black pepper" => "pimenta-do-reino",
  "egg" => "ovo", "eggs" => "ovos",
  "milk" => "leite",
  "heavy cream" => "creme de leite",
  "cream cheese" => "cream cheese",
  "sour cream" => "creme azedo",
  "water" => "água",
  "honey" => "mel",
  "maple syrup" => "xarope de bordo",
  "cocoa powder" => "cacau em pó",
  "chocolate chips" => "gotas de chocolate",
  "dark chocolate" => "chocolate amargo",
  "white chocolate" => "chocolate branco",
  "peanut butter" => "manteiga de amendoim",
  "lemon juice" => "suco de limão",
  "lime juice" => "suco de lima",
  "lemon" => "limão", "lemons" => "limões",
  "lime" => "lima", "limes" => "limas",
  "orange" => "laranja", "oranges" => "laranjas",
  "garlic" => "alho",
  "onion" => "cebola", "onions" => "cebolas",
  "tomato" => "tomate", "tomatoes" => "tomates",
  "cinnamon" => "canela",
  "nutmeg" => "noz-moscada",
  "ginger" => "gengibre",
  "turmeric" => "cúrcuma",
  "cumin" => "cominho",
  "paprika" => "páprica",
  "oregano" => "orégano",
  "basil" => "manjericão",
  "parsley" => "salsinha",
  "cilantro" => "coentro",
  "mint" => "hortelã",
  "thyme" => "tomilho",
  "rosemary" => "alecrim",
  "avocado" => "abacate", "avocados" => "abacates",
  "banana" => "banana", "bananas" => "bananas",
  "strawberry" => "morango", "strawberries" => "morangos",
  "blueberry" => "mirtilo", "blueberries" => "mirtilos",
  "raspberry" => "framboesa", "raspberries" => "framboesas",
  "mango" => "manga",
  "pineapple" => "abacaxi",
  "peach" => "pêssego", "peaches" => "pêssegos",
  "apple" => "maçã", "apples" => "maçãs",
  "cherry" => "cereja", "cherries" => "cerejas",
  "coconut" => "coco",
  "coconut milk" => "leite de coco",
  "coconut cream" => "creme de coco",
  "rice" => "arroz",
  "pasta" => "massa",
  "bread" => "pão",
  "oats" => "aveia",
  "chicken" => "frango",
  "beef" => "carne bovina",
  "pork" => "porco",
  "salmon" => "salmão",
  "shrimp" => "camarão",
  "tofu" => "tofu",
  "chickpeas" => "grão-de-bico",
  "lentils" => "lentilhas",
  "black beans" => "feijão preto",
  "walnuts" => "nozes",
  "almonds" => "amêndoas",
  "cashews" => "castanhas de caju",
  "pecans" => "nozes-pecã",
  "whipped cream" => "chantilly",
  "cream" => "creme",
  "cheese" => "queijo",
  "brewed coffee" => "café coado",
  "coffee" => "café",
  "tea" => "chá",
  "ice" => "gelo",
  "ice cubes" => "cubos de gelo",
  "frozen" => "congelado",
  "fresh" => "fresco",
  "chopped" => "picado",
  "diced" => "cortado em cubos",
  "minced" => "picado finamente",
  "sliced" => "fatiado",
  "grated" => "ralado",
  "melted" => "derretido",
  "softened" => "amolecido",
  "room temperature" => "temperatura ambiente",
  "optional" => "opcional",
  "sweetener" => "adoçante",
  "sweetener of choice" => "adoçante de sua preferência",

  # Cooking instructions
  "Preheat the oven to" => "Pré-aqueça o forno a",
  "Preheat oven to" => "Pré-aqueça o forno a",
  "Line a baking sheet with parchment paper" => "Forre uma assadeira com papel manteiga",
  "Grease a" => "Unte um(a)",
  "In a large bowl" => "Em uma tigela grande",
  "In a medium bowl" => "Em uma tigela média",
  "In a small bowl" => "Em uma tigela pequena",
  "In a large saucepan" => "Em uma panela grande",
  "In a large pot" => "Em uma panela grande",
  "In a saucepan" => "Em uma panela",
  "In a blender" => "No liquidificador",
  "In a food processor" => "No processador de alimentos",
  "Mix well" => "Misture bem",
  "Mix until" => "Misture até",
  "Stir well" => "Mexa bem",
  "Stir until" => "Mexa até",
  "Stir in" => "Adicione e mexa",
  "stir occasionally" => "mexendo ocasionalmente",
  "stirring occasionally" => "mexendo ocasionalmente",
  "stirring constantly" => "mexendo constantemente",
  "Combine" => "Combine",
  "Whisk together" => "Bata junto",
  "Whisk" => "Bata",
  "Blend until smooth" => "Bata até ficar homogêneo",
  "Blend" => "Bata",
  "Pour" => "Despeje",
  "Add" => "Adicione",
  "Remove from heat" => "Retire do fogo",
  "Let cool" => "Deixe esfriar",
  "Let it cool" => "Deixe esfriar",
  "Allow to cool" => "Deixe esfriar",
  "Refrigerate" => "Refrigere",
  "refrigerate" => "refrigere",
  "Freeze" => "Congele",
  "Bake for" => "Asse por",
  "bake for" => "asse por",
  "Cook for" => "Cozinhe por",
  "cook for" => "cozinhe por",
  "Simmer" => "Cozinhe em fogo baixo",
  "simmer" => "fogo baixo",
  "Bring to a boil" => "Leve para ferver",
  "bring to a boil" => "leve para ferver",
  "Reduce heat" => "Reduza o fogo",
  "reduce heat" => "reduza o fogo",
  "over medium heat" => "em fogo médio",
  "over low heat" => "em fogo baixo",
  "over high heat" => "em fogo alto",
  "on low heat" => "em fogo baixo",
  "on medium heat" => "em fogo médio",
  "minutes" => "minutos",
  "hours" => "horas",
  "hour" => "hora",
  "Serve" => "Sirva",
  "serve" => "sirva",
  "Enjoy" => "Aproveite",
  "enjoy" => "aproveite",
  "Garnish with" => "Decore com",
  "Top with" => "Cubra com",
  "Sprinkle" => "Polvilhe",
  "Season with" => "Tempere com",
  "season with" => "tempere com",
  "Drain" => "Escorra",
  "Strain" => "Coe",
  "strain" => "coe",
  "Fold in" => "Incorpore",
  "Set aside" => "Reserve",
  "set aside" => "reserve",
  "until golden" => "até dourar",
  "until golden brown" => "até dourar",
  "Decarb your weed" => "Descarboxile sua erva",
  "Decarb" => "Descarboxile",
  "decarb" => "descarboxile",
  "Learn how" => "Saiba como",
  "Not sure" => "Não tem certeza",
  "cheesecloth" => "pano de algodão",
  "parchment paper" => "papel manteiga",
  "baking sheet" => "assadeira",
  "baking pan" => "forma",
  "mixing bowl" => "tigela",
  "saucepan" => "panela",
  "skillet" => "frigideira",
  "frying pan" => "frigideira",
  "cutting board" => "tábua de corte",
}

ES = {
  "cup" => "taza", "cups" => "tazas",
  "tablespoon" => "cucharada", "tablespoons" => "cucharadas",
  "tbsp" => "cucharada",
  "teaspoon" => "cucharadita", "teaspoons" => "cucharaditas",
  "tsp" => "cucharadita",
  "ounce" => "onza", "ounces" => "onzas", "oz" => "oz",
  "pound" => "libra", "pounds" => "libras", "lb" => "lb",
  "pinch" => "pizca",
  "handful" => "puñado",
  "slice" => "rebanada", "slices" => "rebanadas",
  "piece" => "pieza", "pieces" => "piezas",
  "clove" => "diente", "cloves" => "dientes",
  "bunch" => "manojo",
  "can" => "lata",
  "jar" => "frasco",
  "package" => "paquete",
  "stick" => "barra", "sticks" => "barras",
  "dash" => "pizca",
  "to taste" => "al gusto",
  "as needed" => "según sea necesario",

  "ground weed" => "hierba molida",
  "ground cannabis" => "cannabis molida",
  "cannabutter" => "mantequilla de cannabis",
  "cannabis butter" => "mantequilla de cannabis",
  "infused coconut oil" => "aceite de coco infusionado",
  "infused olive oil" => "aceite de oliva infusionado",
  "infused butter" => "mantequilla infusionada",
  "infused honey" => "miel infusionada",
  "infused milk" => "leche infusionada",
  "infused ghee" => "ghee infusionado",
  "infused condensed milk" => "leche condensada infusionada",
  "coconut oil" => "aceite de coco",
  "olive oil" => "aceite de oliva",
  "unsalted butter" => "mantequilla sin sal",
  "butter" => "mantequilla",
  "sugar" => "azúcar",
  "brown sugar" => "azúcar morena",
  "powdered sugar" => "azúcar glass",
  "flour" => "harina",
  "all-purpose flour" => "harina de trigo",
  "almond flour" => "harina de almendra",
  "baking soda" => "bicarbonato de sodio",
  "baking powder" => "polvo para hornear",
  "vanilla extract" => "extracto de vainilla",
  "vanilla" => "vainilla",
  "salt" => "sal",
  "pepper" => "pimienta",
  "black pepper" => "pimienta negra",
  "egg" => "huevo", "eggs" => "huevos",
  "milk" => "leche",
  "heavy cream" => "crema para batir",
  "cream cheese" => "queso crema",
  "sour cream" => "crema agria",
  "water" => "agua",
  "honey" => "miel",
  "maple syrup" => "jarabe de arce",
  "cocoa powder" => "cacao en polvo",
  "chocolate chips" => "chispas de chocolate",
  "dark chocolate" => "chocolate oscuro",
  "white chocolate" => "chocolate blanco",
  "peanut butter" => "mantequilla de maní",
  "lemon juice" => "jugo de limón",
  "lime juice" => "jugo de lima",
  "lemon" => "limón", "lemons" => "limones",
  "lime" => "lima", "limes" => "limas",
  "orange" => "naranja", "oranges" => "naranjas",
  "garlic" => "ajo",
  "onion" => "cebolla", "onions" => "cebollas",
  "tomato" => "tomate", "tomatoes" => "tomates",
  "cinnamon" => "canela",
  "nutmeg" => "nuez moscada",
  "ginger" => "jengibre",
  "turmeric" => "cúrcuma",
  "cumin" => "comino",
  "paprika" => "pimentón",
  "oregano" => "orégano",
  "basil" => "albahaca",
  "parsley" => "perejil",
  "cilantro" => "cilantro",
  "mint" => "menta",
  "thyme" => "tomillo",
  "rosemary" => "romero",
  "avocado" => "aguacate", "avocados" => "aguacates",
  "banana" => "plátano", "bananas" => "plátanos",
  "strawberry" => "fresa", "strawberries" => "fresas",
  "blueberry" => "arándano", "blueberries" => "arándanos",
  "raspberry" => "frambuesa", "raspberries" => "frambuesas",
  "mango" => "mango",
  "pineapple" => "piña",
  "peach" => "durazno", "peaches" => "duraznos",
  "apple" => "manzana", "apples" => "manzanas",
  "cherry" => "cereza", "cherries" => "cerezas",
  "coconut" => "coco",
  "coconut milk" => "leche de coco",
  "coconut cream" => "crema de coco",
  "rice" => "arroz",
  "pasta" => "pasta",
  "bread" => "pan",
  "oats" => "avena",
  "chicken" => "pollo",
  "beef" => "carne de res",
  "pork" => "cerdo",
  "salmon" => "salmón",
  "shrimp" => "camarones",
  "tofu" => "tofu",
  "chickpeas" => "garbanzos",
  "lentils" => "lentejas",
  "black beans" => "frijoles negros",
  "walnuts" => "nueces",
  "almonds" => "almendras",
  "cashews" => "anacardos",
  "pecans" => "nueces pecanas",
  "whipped cream" => "crema batida",
  "cream" => "crema",
  "cheese" => "queso",
  "brewed coffee" => "café preparado",
  "coffee" => "café",
  "tea" => "té",
  "ice" => "hielo",
  "ice cubes" => "cubos de hielo",
  "frozen" => "congelado",
  "fresh" => "fresco",
  "chopped" => "picado",
  "diced" => "cortado en cubos",
  "minced" => "picado finamente",
  "sliced" => "rebanado",
  "grated" => "rallado",
  "melted" => "derretido",
  "softened" => "ablandado",
  "room temperature" => "temperatura ambiente",
  "optional" => "opcional",
  "sweetener" => "endulzante",
  "sweetener of choice" => "endulzante de su preferencia",

  "Preheat the oven to" => "Precaliente el horno a",
  "Preheat oven to" => "Precaliente el horno a",
  "Line a baking sheet with parchment paper" => "Forre una bandeja para hornear con papel pergamino",
  "Grease a" => "Engrase un(a)",
  "In a large bowl" => "En un tazón grande",
  "In a medium bowl" => "En un tazón mediano",
  "In a small bowl" => "En un tazón pequeño",
  "In a large saucepan" => "En una olla grande",
  "In a large pot" => "En una olla grande",
  "In a saucepan" => "En una olla",
  "In a blender" => "En una licuadora",
  "In a food processor" => "En un procesador de alimentos",
  "Mix well" => "Mezcle bien",
  "Mix until" => "Mezcle hasta",
  "Stir well" => "Revuelva bien",
  "Stir until" => "Revuelva hasta",
  "Stir in" => "Agregue y revuelva",
  "stir occasionally" => "revolviendo ocasionalmente",
  "stirring occasionally" => "revolviendo ocasionalmente",
  "stirring constantly" => "revolviendo constantemente",
  "Combine" => "Combine",
  "Whisk together" => "Bata junto",
  "Whisk" => "Bata",
  "Blend until smooth" => "Licúe hasta que quede suave",
  "Blend" => "Licúe",
  "Pour" => "Vierta",
  "Add" => "Agregue",
  "Remove from heat" => "Retire del fuego",
  "Let cool" => "Deje enfriar",
  "Let it cool" => "Deje enfriar",
  "Allow to cool" => "Deje enfriar",
  "Refrigerate" => "Refrigere",
  "refrigerate" => "refrigere",
  "Freeze" => "Congele",
  "Bake for" => "Hornee por",
  "bake for" => "hornee por",
  "Cook for" => "Cocine por",
  "cook for" => "cocine por",
  "Simmer" => "Cocine a fuego lento",
  "simmer" => "fuego lento",
  "Bring to a boil" => "Lleve a ebullición",
  "bring to a boil" => "lleve a ebullición",
  "Reduce heat" => "Reduzca el fuego",
  "reduce heat" => "reduzca el fuego",
  "over medium heat" => "a fuego medio",
  "over low heat" => "a fuego bajo",
  "over high heat" => "a fuego alto",
  "on low heat" => "a fuego bajo",
  "on medium heat" => "a fuego medio",
  "minutes" => "minutos",
  "hours" => "horas",
  "hour" => "hora",
  "Serve" => "Sirva",
  "serve" => "sirva",
  "Enjoy" => "Disfrute",
  "enjoy" => "disfrute",
  "Garnish with" => "Decore con",
  "Top with" => "Cubra con",
  "Sprinkle" => "Espolvoree",
  "Season with" => "Sazone con",
  "season with" => "sazone con",
  "Drain" => "Escurra",
  "Strain" => "Cuele",
  "strain" => "cuele",
  "Fold in" => "Incorpore",
  "Set aside" => "Reserve",
  "set aside" => "reserve",
  "until golden" => "hasta dorar",
  "until golden brown" => "hasta que esté dorado",
  "Decarb your weed" => "Descarboxile su hierba",
  "Decarb" => "Descarboxile",
  "decarb" => "descarboxile",
  "Learn how" => "Aprenda cómo",
  "Not sure" => "¿No está seguro?",
  "cheesecloth" => "manta de cielo",
  "parchment paper" => "papel pergamino",
  "baking sheet" => "bandeja para hornear",
  "baking pan" => "molde para hornear",
  "mixing bowl" => "tazón",
  "saucepan" => "olla",
  "skillet" => "sartén",
  "frying pan" => "sartén",
  "cutting board" => "tabla de cortar",
}

DE = {
  "cup" => "Tasse", "cups" => "Tassen",
  "tablespoon" => "Esslöffel", "tablespoons" => "Esslöffel",
  "tbsp" => "EL",
  "teaspoon" => "Teelöffel", "teaspoons" => "Teelöffel",
  "tsp" => "TL",
  "ounce" => "Unze", "ounces" => "Unzen", "oz" => "oz",
  "pound" => "Pfund", "pounds" => "Pfund", "lb" => "lb",
  "pinch" => "Prise",
  "handful" => "Handvoll",
  "slice" => "Scheibe", "slices" => "Scheiben",
  "piece" => "Stück", "pieces" => "Stücke",
  "clove" => "Zehe", "cloves" => "Zehen",
  "bunch" => "Bund",
  "can" => "Dose",
  "jar" => "Glas",
  "package" => "Packung",
  "stick" => "Stange", "sticks" => "Stangen",
  "dash" => "Spritzer",
  "to taste" => "nach Geschmack",
  "as needed" => "nach Bedarf",

  "ground weed" => "gemahlenes Cannabis",
  "ground cannabis" => "gemahlenes Cannabis",
  "cannabutter" => "Cannabutter",
  "cannabis butter" => "Cannabutter",
  "infused coconut oil" => "infundiertes Kokosöl",
  "infused olive oil" => "infundiertes Olivenöl",
  "infused butter" => "infundierte Butter",
  "infused honey" => "infundierter Honig",
  "infused milk" => "infundierte Milch",
  "infused ghee" => "infundiertes Ghee",
  "infused condensed milk" => "infundierte Kondensmilch",
  "coconut oil" => "Kokosöl",
  "olive oil" => "Olivenöl",
  "unsalted butter" => "ungesalzene Butter",
  "butter" => "Butter",
  "sugar" => "Zucker",
  "brown sugar" => "brauner Zucker",
  "powdered sugar" => "Puderzucker",
  "flour" => "Mehl",
  "all-purpose flour" => "Allzweckmehl",
  "almond flour" => "Mandelmehl",
  "baking soda" => "Natron",
  "baking powder" => "Backpulver",
  "vanilla extract" => "Vanilleextrakt",
  "vanilla" => "Vanille",
  "salt" => "Salz",
  "pepper" => "Pfeffer",
  "black pepper" => "schwarzer Pfeffer",
  "egg" => "Ei", "eggs" => "Eier",
  "milk" => "Milch",
  "heavy cream" => "Sahne",
  "cream cheese" => "Frischkäse",
  "sour cream" => "saure Sahne",
  "water" => "Wasser",
  "honey" => "Honig",
  "maple syrup" => "Ahornsirup",
  "cocoa powder" => "Kakaopulver",
  "chocolate chips" => "Schokoladenstückchen",
  "dark chocolate" => "Zartbitterschokolade",
  "white chocolate" => "weiße Schokolade",
  "peanut butter" => "Erdnussbutter",
  "lemon juice" => "Zitronensaft",
  "lime juice" => "Limettensaft",
  "lemon" => "Zitrone", "lemons" => "Zitronen",
  "lime" => "Limette", "limes" => "Limetten",
  "orange" => "Orange", "oranges" => "Orangen",
  "garlic" => "Knoblauch",
  "onion" => "Zwiebel", "onions" => "Zwiebeln",
  "tomato" => "Tomate", "tomatoes" => "Tomaten",
  "cinnamon" => "Zimt",
  "nutmeg" => "Muskatnuss",
  "ginger" => "Ingwer",
  "turmeric" => "Kurkuma",
  "cumin" => "Kreuzkümmel",
  "paprika" => "Paprika",
  "oregano" => "Oregano",
  "basil" => "Basilikum",
  "parsley" => "Petersilie",
  "cilantro" => "Koriander",
  "mint" => "Minze",
  "thyme" => "Thymian",
  "rosemary" => "Rosmarin",
  "avocado" => "Avocado", "avocados" => "Avocados",
  "banana" => "Banane", "bananas" => "Bananen",
  "strawberry" => "Erdbeere", "strawberries" => "Erdbeeren",
  "blueberry" => "Blaubeere", "blueberries" => "Blaubeeren",
  "raspberry" => "Himbeere", "raspberries" => "Himbeeren",
  "mango" => "Mango",
  "pineapple" => "Ananas",
  "peach" => "Pfirsich", "peaches" => "Pfirsiche",
  "apple" => "Apfel", "apples" => "Äpfel",
  "cherry" => "Kirsche", "cherries" => "Kirschen",
  "coconut" => "Kokos",
  "coconut milk" => "Kokosmilch",
  "coconut cream" => "Kokoscreme",
  "rice" => "Reis",
  "pasta" => "Pasta",
  "bread" => "Brot",
  "oats" => "Haferflocken",
  "chicken" => "Hähnchen",
  "beef" => "Rindfleisch",
  "pork" => "Schweinefleisch",
  "salmon" => "Lachs",
  "shrimp" => "Garnelen",
  "tofu" => "Tofu",
  "chickpeas" => "Kichererbsen",
  "lentils" => "Linsen",
  "black beans" => "schwarze Bohnen",
  "walnuts" => "Walnüsse",
  "almonds" => "Mandeln",
  "cashews" => "Cashewnüsse",
  "pecans" => "Pekannüsse",
  "whipped cream" => "Schlagsahne",
  "cream" => "Sahne",
  "cheese" => "Käse",
  "brewed coffee" => "aufgebrühter Kaffee",
  "coffee" => "Kaffee",
  "tea" => "Tee",
  "ice" => "Eis",
  "ice cubes" => "Eiswürfel",
  "frozen" => "gefroren",
  "fresh" => "frisch",
  "chopped" => "gehackt",
  "diced" => "gewürfelt",
  "minced" => "fein gehackt",
  "sliced" => "in Scheiben geschnitten",
  "grated" => "gerieben",
  "melted" => "geschmolzen",
  "softened" => "weich",
  "room temperature" => "Raumtemperatur",
  "optional" => "optional",
  "sweetener" => "Süßungsmittel",
  "sweetener of choice" => "Süßungsmittel nach Wahl",

  "Preheat the oven to" => "Heizen Sie den Ofen auf",
  "Preheat oven to" => "Heizen Sie den Ofen auf",
  "Line a baking sheet with parchment paper" => "Legen Sie ein Backblech mit Backpapier aus",
  "Grease a" => "Fetten Sie ein(e)",
  "In a large bowl" => "In einer großen Schüssel",
  "In a medium bowl" => "In einer mittelgroßen Schüssel",
  "In a small bowl" => "In einer kleinen Schüssel",
  "In a large saucepan" => "In einem großen Topf",
  "In a large pot" => "In einem großen Topf",
  "In a saucepan" => "In einem Topf",
  "In a blender" => "In einem Mixer",
  "In a food processor" => "In einer Küchenmaschine",
  "Mix well" => "Gut mischen",
  "Mix until" => "Mischen bis",
  "Stir well" => "Gut umrühren",
  "Stir until" => "Rühren bis",
  "Stir in" => "Einrühren",
  "stir occasionally" => "gelegentlich umrühren",
  "stirring occasionally" => "gelegentlich umrühren",
  "stirring constantly" => "ständig rühren",
  "Combine" => "Vermischen",
  "Whisk together" => "Zusammen verquirlen",
  "Whisk" => "Verquirlen",
  "Blend until smooth" => "Mixen bis eine glatte Masse entsteht",
  "Blend" => "Mixen",
  "Pour" => "Gießen",
  "Add" => "Hinzufügen",
  "Remove from heat" => "Vom Herd nehmen",
  "Let cool" => "Abkühlen lassen",
  "Let it cool" => "Abkühlen lassen",
  "Allow to cool" => "Abkühlen lassen",
  "Refrigerate" => "Kühlen",
  "refrigerate" => "kühlen",
  "Freeze" => "Einfrieren",
  "Bake for" => "Backen für",
  "bake for" => "backen für",
  "Cook for" => "Kochen für",
  "cook for" => "kochen für",
  "Simmer" => "Köcheln lassen",
  "simmer" => "köcheln",
  "Bring to a boil" => "Zum Kochen bringen",
  "bring to a boil" => "zum Kochen bringen",
  "Reduce heat" => "Hitze reduzieren",
  "reduce heat" => "Hitze reduzieren",
  "over medium heat" => "bei mittlerer Hitze",
  "over low heat" => "bei niedriger Hitze",
  "over high heat" => "bei hoher Hitze",
  "on low heat" => "bei niedriger Hitze",
  "on medium heat" => "bei mittlerer Hitze",
  "minutes" => "Minuten",
  "hours" => "Stunden",
  "hour" => "Stunde",
  "Serve" => "Servieren",
  "serve" => "servieren",
  "Enjoy" => "Genießen",
  "enjoy" => "genießen",
  "Garnish with" => "Garnieren mit",
  "Top with" => "Belegen mit",
  "Sprinkle" => "Bestreuen",
  "Season with" => "Würzen mit",
  "season with" => "würzen mit",
  "Drain" => "Abtropfen lassen",
  "Strain" => "Abseihen",
  "strain" => "abseihen",
  "Fold in" => "Unterheben",
  "Set aside" => "Beiseite stellen",
  "set aside" => "beiseite stellen",
  "until golden" => "bis goldbraun",
  "until golden brown" => "bis goldbraun",
  "Decarb your weed" => "Decarboxylieren Sie Ihr Cannabis",
  "Decarb" => "Decarboxylieren",
  "decarb" => "decarboxylieren",
  "Learn how" => "Erfahren Sie wie",
  "Not sure" => "Nicht sicher?",
  "cheesecloth" => "Seihtuch",
  "parchment paper" => "Backpapier",
  "baking sheet" => "Backblech",
  "baking pan" => "Backform",
  "mixing bowl" => "Schüssel",
  "saucepan" => "Topf",
  "skillet" => "Pfanne",
  "frying pan" => "Bratpfanne",
  "cutting board" => "Schneidebrett",
}

def translate_text(text, dict)
  result = text.dup
  # Sort by length descending so longer phrases match first
  sorted_keys = dict.keys.sort_by { |k| -k.length }
  sorted_keys.each do |en|
    translated = dict[en]
    # Word boundary matching (case-sensitive for multi-word, flexible for single)
    if en.include?(" ")
      result.gsub!(/#{Regexp.escape(en)}/, translated)
    else
      result.gsub!(/\b#{Regexp.escape(en)}\b/, translated)
    end
  end
  result
end

DICTS = { "pt" => PT, "es" => ES, "de" => DE }

DICTS.each do |lang, dict|
  i18n_file = File.join(I18N_DIR, "recipes_#{lang}.json")
  i18n = JSON.parse(File.read(i18n_file))

  recipes.each do |slug, recipe|
    i18n[slug] ||= {}

    translated_ings = recipe["ingredients"].map { |ing| translate_text(ing, dict) }
    translated_ins = recipe["instructions"].map { |ins| translate_text(ins, dict) }

    i18n[slug]["ingredients"] = translated_ings
    i18n[slug]["instructions"] = translated_ins
  end

  File.write(i18n_file, JSON.pretty_generate(i18n))
  puts "#{lang}: translated #{recipes.count} recipes (ingredients + instructions)"
end

puts "Done!"
